# Generated by Django 4.1 on 2023-05-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
